camera_1:
    frame_size: [1920, 1080]
    link: rtsp://cdn01-obmen-video-echd.mos.ru:1554/BCLQJSXWNGJQIM2MYX5HJBVT6J7U6LP4PGRTBKPADH7ZM4LKWYEJKS6H7BLQO6ALOUZUZ75KKBRMLBASQUPBMN5G5FQPOKU52E3OKHNU5YN3SFSZPIPRBBR6VK2JJLF2HFES4HQ363H4FGKFUVOIFQQVKY5PCTX2N4QZDECSHUZI3VKCED46YQPO3XLX7NBSP7NNJ62OB2KFLF37AHGY7NUBRIT7LL4X7TLXXRMA7YM6CCLXSFACHTRJG2FHPRFY/27428d7ff1fad07397bf68f112da3d3f-public
    task: ['ppl', 'pose']
    crane_id: 1
    side: 1 # ±1 (front or rear) only necessary if task contains aruco
    detection_zones:
        warning: [[1,2,3]]
        danger: [[1,2,3]]

camera_2:
    frame_size: [1920, 1080]
    link: rtsp://cdn02-obmen-video-echd.mos.ru:1554/E55EKE2PCSM2GGJD7MIQTLFU3V7U6LP4PGRTBKPADH7ZM4LKWYEMRTQWKQRQ6HHPNEQV5GM53KUV7KTYC2HD47KRAF3A2N32QYSINB6TM634D6BNV6ME2LRG6MS7KZZ6KTO7B4RQZ6YCRUQG3NHWTDSDWQ5PCTX2N4QZDECSHUZI3VKCED47GIM756HGTG74VA46QLCOEH4JNF37AHGY7NUBRIT7LL4X7TLXXRMA7YM6CCLXSFACHTRJG2FHPRFY/fd6fce06dcb2d987cd6dc9c4c7e86ddd-public
    task: ['ppl', 'pose']
    crane_id: 1
    side: -1 # ±1 (front or rear) only necessary if task contains aruco
    detection_zones:
        warning: [[1,2,3]]
        danger: [[1,2,3]]

camera_3:
    frame_size: [1920, 1080]
    link: rtsp://cdn01-obmen-video-echd.mos.ru:1554/BCLQJSXWNGJQIM2MYX5HJBVT6J7U6LP4PGRTBKPADH7ZM4LKWYED5L2MP5WYXLB2A65ZN6RWKNV2NYZ7LH5N354DZWIYNA53MO72FRHXNG3QVJG47JUXCQ65VXNUS53HWTJBXILHJ5CKOV2MG32RKVYDXU5PCTX2N4QZDECSHUZI3VKCED4VIML6ATMXENZ3QBI3ZYPEF3PLVZ2ZQPAQJC3F7AKVW5CJS6Z5OMWBEAR25P4YIKLXR5FOIGOWUKEO/59785d8be65b1bfd41768c2c1b1eefef-public
    task: ['ppl']
    crane_id: 0
    side: 1 # ±1 (front or rear) only necessary if task contains aruco
    detection_zones:
        warning: [[1,2,3]]
        danger: [[1,2,3]]

camera_4:
    frame_size: [1920, 1080]
    link: rtsp://cdn01-obmen-video-echd.mos.ru:1554/BCLQJSXWNGJQIM2MYX5HJBVT6J7U6LP4PGRTBKPADH7ZM4LKWYENIRFOL2WWA3U56ZY7UB6LHVDXNFLLQ3CX3NX5IRR7ZRHX5T3S3JIEVDFRZMRCI5RLWEHZGJOQ45DUJV5KU43GXE4MD3QPCB7ZU5LP6A5PCTX2N4QZDECSHUZI3VKCED4UL7MYLFN7PLAHWXSUN6UKOYYVXZ2ZQPAQJC3F7AKVW5CJS6Z5OMWBEAR25P4YIKLXR5FOIGOWUKEO/7b8b2d7e0aa302c85e7b1ee09ea24c1c-public
    task: ['ppl', 'pose']
    crane_id: 2
    side: 1 # ±1 (front or rear) only necessary if task contains aruco
    detection_zones:
        warning: [[1,2,3]]
        danger: [[1,2,3]]
