camera_1:
    frame_size: [1920, 1080]
    link: rtsp://example.com
    task: ['ppl', 'pose']
    crane_id: 1
    side: 1 # ±1 (front or rear) only necessary if task contains aruco
    detection_zones:
        warning: [[1,2,3]]
        danger: [[1,2,3]]

camera_2:
    frame_size: [1920, 1080]
    link: rtsp://example.com
    task: ['ppl', 'pose']
    crane_id: 1
    side: -1 # ±1 (front or rear) only necessary if task contains aruco
    detection_zones:
        warning: [[1,2,3]]
        danger: [[1,2,3]]

camera_3:
    frame_size: [1920, 1080]
    link: rtsp://example.com
    task: ['ppl']
    crane_id: 0
    side: 1 # ±1 (front or rear) only necessary if task contains aruco
    detection_zones:
        warning: [[1,2,3]]
        danger: [[1,2,3]]

camera_4:
    frame_size: [1920, 1080]
    link: rtsp://example.com
    task: ['ppl', 'pose']
    crane_id: 2
    side: 1 # ±1 (front or rear) only necessary if task contains aruco
    detection_zones:
        warning: [[1,2,3]]
        danger: [[1,2,3]]
