fps: 4
api_url: http://service:4000/api/cv

detector:
    model_path: /usr/src/app_new/models/v8m_crowd_v5_albu_vbox.pt
    inference_imgsz: 960
    inference_conf: 0.7
    inference_bs: 28
    orig_img_h: 720
    orig_img_w: 1280
    device: cuda:0
    time_logging_period: 100

pose_estimator:
    # путь к матрице калибровки
    calibration_matrix_path: "/usr/src/app_new/cranpose/calib/calibration_matrix_hikvision.npy"
    # путь к коэффициентам дисторсии
    distortion_coefficients_path: "/usr/src/app_new/cranpose/calib/distortion_coefficients_hikvision.npy"
    # длина стороны маркера в метрах
    edge_len: 0.7
    # шаг, с которым маркеры установлены
    marker_step: 10
    # максимальное число маркеров
    n_markers: 100
    # Тип аруко маркера
    aruco_dict_type: DICT_7X7_100
    # Позиции маркеров в метрах
    poses:
        31: 0.
        30: 9.6
        29: 19.6
        28: 29.53
        27: 39.52
        26: 48.52
        25: 58.03
        24: 67.23
        23: 76.65
        22: 86.65
        21: 96.6

debug: # Only if debug option is set
    save_img_path: /usr/src/app_new/logs/debug
